services:
  computer-react:
    container_name: computer-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9008:9008"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - ./src:/app/src 
    stdin_open: true
    tty: true