services:
  computer-monitoring:
    build:
      context: ./
      dockerfile: Dockerfile
    image: computer-monitoring
    container_name: computer-server
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /mnt/nvme0n1/computerMonitoringUploads/users-profile:/var/www/public/users-profile
    networks:
      - computer
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1  # Replace with your host's IP if necessary
      DB_PORT: 3306
      DB_DATABASE: computer_monitoring
      DB_USERNAME: smct
      DB_PASSWORD: smct
      APP_DEBUG: "false"
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 465
      MAIL_USERNAME: smctitprojects@gmail.com
      MAIL_PASSWORD: ztkatlxgziwgujcv
      MAIL_ENCRYPTION: ssl
      MAIL_FROM_ADDRESS: smctitprojects@gmail.com
      MAIL_FROM_NAME: "SMCT Computer Monitoring"
      APP_NAME: "Computer Monitoring"
      APP_ENV: production
      APP_KEY: base64:3G78vyaYwAqjiflGWVVrS4y1WqBqwwHva2B0/JmPFc0=
      APP_TIMEZONE: UTC
      APP_URL: https://comonitoringserver.smctgroup.ph



  computer-nginx:
    image: nginx:alpine
    container_name: computer-nginx
    restart: unless-stopped
    ports:
      - 9002:9002
    volumes:
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
      - /mnt/nvme0n1/computerMonitoringUploads/users-profile:/mnt/nvme0n1/computerMonitoringUploads/users-profile
    networks:
      - computer

volumes:
  computer_data:

networks:
  computer:
    driver: bridge